// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtjoeazrgdqvubytwogh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0am9lYXpyZ2RxdnVieXR3b2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzQ5NzksImV4cCI6MjA3NDkxMDk3OX0.lMVpDTLNsk_nPCn3QCiGJ0o7TbY-hJEiQWtjJcxeV6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});